name: Sincronizar com Reposit贸rio Vercel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c贸digo original
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push para o reposit贸rio c贸pia
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '.'
          destination-github-username: 'dravoai'
          destination-repository-name: 'propwealthaireal'
          user-email: 'mariopereiradasilvamanuel@gmail.com'
          target-branch: 'main'
